### ISSUE TITLE
Document dependency updates procedure

### ISSUE THREAD

**Issue by samuelallan72** [canonical/snap-tempest#111]
We have github action based processes for opening PRs with dependency updates, and the standard dependabot updates - eg.:

- `release(antelope): update snapcraft.yaml`
- chore(deps): bump confluent-kafka from 1.8.2 to 2.3.0`

There are considerations for reviewing these, and useful details about the processes, such as:

- Tempest guarantees backward compatibility until `<release-last>` tag is issued. Then that version will be the last supporting version for that release
  - https://docs.openstack.org/tempest/latest/tempest_and_plugins_compatible_version_policy.html
- for dependency updates for plugins, you should check each repo to confirm the latest tag has indeed been picked and check the release notes

We should document these, probably in a CONTRIBUTING.md file in the repo.

**Comment by aieri** [comment]
partially fixed by #156
