### ISSUE TITLE
Remove `tools` from release branches 

### ISSUE THREAD

**Issue by agileshaw** [canonical/snap-tempest#131]
In CI workflow, we are only using the script in `tools` directory from the main branch, so having `stable/*` branches also contain it could lead to confusion, especially when their versions are not in sync. We should investigate the possibility of removing `tools` from those branches, or finding a better solution to handle this.

**Comment by aieri** [comment]
yeah I think it would perhaps be easier to move the update automation in a completely separate repo

**Comment by chanchiwai-ray** [comment]
The work is currently being done in this repo: https://github.com/canonical/snap-tempest-automation

**Comment by aieri** [comment]
all automation has now been moved to https://github.com/canonical/snap-tempest-automation
