### ISSUE TITLE
CODEOWNERS on release branches needs updating

### ISSUE THREAD

**Issue by samuelallan72** [canonical/snap-tempest#184]
The CODEOWNERS file is up to date on the `main` branch, but not for release branches.  This means we miss getting the auto review requested for the automated PRs to update dependencies for releases.

We should implement this using https://github.com/canonical/solutions-engineering-automation , so the files are managed there.  Don't update them directly in this repo.

**Comment by Pjack** [comment]
The codeowner is updated, so close it .
