### ISSUE TITLE
some ussuri/stable tests would fail on ussuri

### ISSUE THREAD

**Issue by jeffreychang911** [canonical/snap-tempest#196]
SolQA test run - https://solutions.qa.canonical.com/testruns/3faf631a-39f3-430b-8a0b-61b4be779fd4
Artifacts - https://oil-jenkins.canonical.com/artifacts/3faf631a-39f3-430b-8a0b-61b4be779fd4/index.html
tempest report - https://oil-jenkins.canonical.com/artifacts/3faf631a-39f3-430b-8a0b-61b4be779fd4/generated/generated/openstack/tempest/run_2/results.html

We deploy snap tempest from ussuri/stable channel to a ussuri-focal env, and run tempest 3 times to confirm same tests failed consistently.
They are : LoadBalancerAPITest, PoolAPITest, MultipleCreateTestJSON, test_upload_too_many_objects, test_server_connectivity_live_migration

However, we have successful results for snap-tempest from yoga-stable channel for ussuri-focal. SolQA would used that as default for now.

**Comment by Pjack** [comment]
It's an old issue that we cannot track it anymore. Welcome to submit new issue or reopen this one when you encounter it again.
